package uk.ac.ox.oucs.search2.event;

import org.sakaiproject.event.api.Event;
import uk.ac.ox.oucs.search2.task.Task;

import java.util.Collection;

/**
 * Component in charge of listening for the Events generated by Sakai and generating Tasks.
 * <p>
 * The IndexEventHandler listens for {@link Event} in Sakai and generate a new {@link Task} which will allow to update
 * the index appropriately.
 * </p>
 *
 * @author Colin Hebert
 */
public interface EventHandler {
    /**
     * Gets all the supported Event names that should be intercepted by this EventHandler.
     *
     * @return Every event that should be listened to and sent to this handler.
     */
    Collection<String> getSupportedEventTypes();

    /**
     * Creates a Task for the given Event.
     * <p>
     * The created {@link Task} will contain all the necessary information to update the index given the {@link Event}.
     * </p>
     *
     * @param event Handled Event
     * @return a Task that will update the index
     */
    Task getTask(Event event);

    /**
     * Checks if this EventHandler can handle a given Event
     * <p>
     * Any kind of {@link Event} can be used as a parameter. It's the responsibility of the developer to check if
     * that Event type matches the types returned by {@link #getSupportedEventTypes()}.
     * </p>
     *
     * @param event Event to check
     * @return true if and only if the event is handled
     */
    boolean isHandled(Event event);
}
