package uk.ac.ox.oucs.search2;

import uk.ac.ox.oucs.search2.filter.SearchFilter;
import uk.ac.ox.oucs.search2.result.SearchResultList;

import java.util.Collection;
import java.util.List;

/**
 * Service used to do full text search in the Sakai instance
 *
 * @author Colin Hebert
 */
public interface SearchService {
    /**
     * Search in the current search engine
     *
     * @param searchQuery full text query
     * @return a list of results (empty if there is no results)
     */
    SearchResultList search(String searchQuery);

    /**
     * Search in the current search engine
     *
     * @param searchQuery full text query
     * @param contexts    contexts (site Ids) in which the search is done
     * @return a list of results (empty if there is no results)
     */
    SearchResultList search(String searchQuery, Collection<String> contexts);

    /**
     * Search in the current search engine
     *
     * @param searchQuery full text query
     * @param context     context (scope) in which the search is done
     * @return a list of results (empty if there is no results)
     */
    SearchResultList search(String searchQuery, SearchContext context);

    /**
     * Search in the current search engine with paging
     *
     * @param searchQuery full text query
     * @param start       index of the first expected result
     * @param length      number of results expected
     * @return a list of results (empty if there is no results)
     */
    SearchResultList search(String searchQuery, long start, long length);

    /**
     * Search in the current search engine with paging
     *
     * @param searchQuery full text query
     * @param contexts    contexts (site Ids) in which the search is done
     * @param start       index of the first expected result
     * @param length      number of results expected
     * @return a list of results (empty if there is no results)
     */
    SearchResultList search(String searchQuery, Collection<String> contexts, long start, long length);

    /**
     * Search in the current search engine with paging
     *
     * @param searchQuery full text query
     * @param context     context (scope) in which the search is done
     * @param start       index of the first expected result
     * @param length      number of results expected
     * @return a list of results (empty if there is no results)
     */
    SearchResultList search(String searchQuery, SearchContext context, long start, long length);

    /**
     * Checks the query against the search engine spellchecker to determine a "did you mean ..." query
     *
     * @param searchQuery Current search query
     * @return a new search query as a String, or null if there is no correction available
     */
    String getSpellCheck(String searchQuery);

    /**
     * Obtains search suggestions provided by the search engine, usually for auto-completion purposes
     *
     * @param searchString Current search query
     * @return list search suggestion ordered by the suggestion score generated by the search engine or
     *         an empty list if there is no suggestions available
     */
    List<String> getSuggestions(String searchString);

    /**
     * Set filters applied on results before being returned.
     * For obvious reasons, it's recommended to have an {@link Iterable} able to provide multiple
     * {@link java.util.Iterator} in the same order
     *
     * @param searchFilters filters to apply on each result
     */
    void setSearchFilters(Iterable<SearchFilter> searchFilters);

    /**
     * Default search contexts
     */
    public enum SearchContext {
        /**
         * Search in the currently displayed site.
         *
         * @deprecated Obtaining the current site is not recommended, instead the siteId should
         */
        @Deprecated
        CURRENT_SITE,
        /**
         * Search in all the sites where the current user is a member
         */
        SUBSCRIBED_SITES,
        /**
         * Search in every accessible site (public sites included)
         */
        ALL_SITES
    }
}
